#!/bin/bash
# Builds Inferno.ipa: compiles the SwiftUI front-end, bundles the emulator
# dylib, ad-hoc signs everything and zips it into an installable payload.
set -euo pipefail

# A library path from the shell's profile (DYLD_LIBRARY_PATH=/opt/homebrew/lib is
# a common one) reaches actool's ibtoold, and on a case-insensitive disk
# Homebrew's libpng.dylib then stands in for ImageIO's own libPng.dylib: ibtoold
# dies with a bus error reading the first PNG and actool exits 255 without a
# word. Nothing here needs such a path.
unset DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/.build"
# Собранный вручную .ipa кладётся в корень проекта: туда за ним приходят руками,
# и это правило проекта (CLAUDE.md).
#
# В CI путь остаётся прежним. Рабочий процесс забирает артефакт из app/ и падает,
# если файла там нет, — ломать его ради местного удобства незачем.
PROJECT="$(cd "$ROOT/.." && pwd)"
if [ -n "${GITHUB_ACTIONS:-}" ]; then
    IPA="$ROOT/Inferno.ipa"
else
    IPA="$PROJECT/Inferno.ipa"
fi
# INFERNO_HVF=1 builds the HVF variant for M1/M2 iPads on iPadOS up to 16.3.1:
# the emulator library built with -Dhvf=enabled, the reimplemented
# Hypervisor.framework beside it, and the private hypervisor entitlement. It is
# meant for TrollStore, so it comes out as a .tipa, and under a name of its own
# so it never overwrites the ordinary Inferno.ipa.
HVF="${INFERNO_HVF:-}"
LIBDIR=inferno
ENTITLEMENTS="$ROOT/Resources/entitlements.plist"
if [ -n "$HVF" ]; then
    IPA="$(dirname "$IPA")/Inferno-HVF.tipa"
    LIBDIR=inferno-hvf
    ENTITLEMENTS="$ROOT/Resources/entitlements-hvf.plist"
fi
# Ищем библиотеку эмулятора там, где она обычно и лежит: сначала рядом с
# репозиторием, как описано в README, потом в дереве сборки. Переопределяется
# переменной INFERNO_DYLIB.
DYLIB="${INFERNO_DYLIB:-}"
if [ -z "$DYLIB" ]; then
    for candidate in \
        "$ROOT/../build/$LIBDIR/libqemu-aarch64-softmmu.dylib" \
        "$HOME/inferno-ios/build/$LIBDIR/libqemu-aarch64-softmmu.dylib"
    do
        [ -f "$candidate" ] && DYLIB="$candidate" && break
    done
fi
# The HVF variant's framework, from an xcodebuild archive of utmapp/Hypervisor.
# Overridden by INFERNO_HYPERVISOR.
HYPERVISOR="${INFERNO_HYPERVISOR:-}"
if [ -n "$HVF" ] && [ -z "$HYPERVISOR" ]; then
    for candidate in \
        "$ROOT/../build/hypervisor/Frameworks/Hypervisor.framework" \
        "$HOME/inferno-ios/build/hypervisor/Frameworks/Hypervisor.framework"
    do
        [ -d "$candidate" ] && HYPERVISOR="$candidate" && break
    done
    [ -n "$HYPERVISOR" ] || {
        echo "No Hypervisor.framework for the HVF build. Build utmapp/Hypervisor or set INFERNO_HYPERVISOR=" >&2
        exit 1
    }
fi
APP="$BUILD/Payload/Inferno.app"
SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
TARGET="arm64-apple-ios16.0"

[ -n "$DYLIB" ] && [ -f "$DYLIB" ] || {
    echo "Нет библиотеки эмулятора. Соберите её или укажите INFERNO_DYLIB=" >&2
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$APP/Frameworks"

echo "==> Компиляция"
# A stamp in the log removes any doubt about which build is actually running.
STAMP="$(date '+%Y-%m-%d %H:%M:%S')"
cat > "$ROOT/Sources/BuildInfo.swift" <<EOF
// Generated by build.sh — do not edit.
enum BuildInfo {
    static let stamp = "$STAMP"
}
EOF
# InfernoPatch: the iOS 26 JIT region (brk calls to StikDebug), in C because
# Swift has no inline assembly. JIT.swift reaches it by @_silgen_name.
mkdir -p "$BUILD/native"
xcrun --sdk iphoneos clang -target "$TARGET" -isysroot "$SDK" -O2 \
    -c "$ROOT/Native/jit26.c" -o "$BUILD/native/jit26.o"
xcrun --sdk iphoneos swiftc \
    -target "$TARGET" \
    -sdk "$SDK" \
    -O -wmo \
    -parse-as-library \
    -o "$APP/Inferno" \
    "$ROOT"/Sources/*.swift \
    "$BUILD/native/jit26.o"

echo "==> Сборка бандла"
cp "$ROOT/Resources/Info.plist" "$APP/Info.plist"
# The StikDebug script the app sends inline when it relaunches itself.
cp "$ROOT/Resources/inferno-jit.js" "$APP/inferno-jit.js"
cp "$DYLIB" "$APP/Frameworks/"
# The library finds the framework through @loader_path, so beside it.
if [ -n "$HVF" ]; then cp -R "$HYPERVISOR" "$APP/Frameworks/"; fi
chmod +x "$APP/Inferno"

# The two programs that run inside the guest, in the restore ramdisk: our
# daemon and ChefKiss's filesystem patcher, which it starts once the restore
# has finished writing. RestoreRamdisk.swift puts them into a copy of the
# ramdisk; nothing here runs on the phone itself.
#
# Both are ad-hoc signed, and that is not cosmetic: AMFI in the guest kills an
# unsigned process the moment it execs, silently, and a parent sees the same
# exit status a clean run would give.
#
# The patcher is ChefKiss's, AGPL-3.0, built from their tree unmodified --
# beside the repository as the README has it, or wherever
# INFERNO_FS_PATCHER_SRC points.
PATCHER_SRC="${INFERNO_FS_PATCHER_SRC:-}"
if [ -z "$PATCHER_SRC" ]; then
    for candidate in \
        "$ROOT/../tools/InfernoFSPatcher" \
        "$HOME/inferno-ios/tools/InfernoFSPatcher"
    do
        [ -d "$candidate/src" ] && PATCHER_SRC="$candidate" && break
    done
fi
[ -n "$PATCHER_SRC" ] && [ -f "$PATCHER_SRC/src/main.cpp" ] || {
    echo "Нет исходников InfernoFSPatcher. Склонируйте их или укажите INFERNO_FS_PATCHER_SRC=" >&2
    exit 1
}
mkdir -p "$APP/guest"
# arm64e and iOS 14: the guest is an emulated iPhone 11 running the firmware
# being restored, not the phone this app is installed on.
xcrun --sdk iphoneos clang -arch arm64e -isysroot "$SDK" -mios-version-min=14.0 -O2 \
    -o "$APP/guest/inferno_patcher" "$ROOT/guest/patcher-daemon.c"
xcrun --sdk iphoneos clang++ -arch arm64e -isysroot "$SDK" -mios-version-min=14.0 -O2 \
    -std=c++17 -o "$APP/guest/inferno_fs_patcher" "$PATCHER_SRC/src/main.cpp"
codesign -f -s - "$APP/guest/inferno_patcher"
codesign -f -s - "$APP/guest/inferno_fs_patcher"

# QEMU's data directory. Inferno drops the keymaps from its tree, but the VNC
# server still refuses to start without them, so take them from a stock QEMU.
KEYMAPS="${INFERNO_KEYMAPS:-/opt/homebrew/share/qemu/keymaps}"
[ -d "$KEYMAPS" ] || { echo "Нет keymap-файлов: $KEYMAPS" >&2; exit 1; }
mkdir -p "$APP/qemu-data"
cp -R "$KEYMAPS" "$APP/qemu-data/keymaps"

# No boot splash. Inferno's splash artwork belongs to ChefKiss and may not be
# shipped in derivative builds (ui/icons/CKBrandingNotice.md in the emulator
# tree); the fork starts without it.

# App icon. Two sources, same actool-compile-then-merge-partial-plist dance:
# the Info.plist keys actool wants come back in a partial plist, merged
# rather than transcribed so a change to the icon needs no change here.
#
#   Inferno.icon   — Icon Composer's bundle, iOS 26's Liquid Glass layers.
#                    Only actool from Xcode 26+ can compile it.
#   Assets.xcassets — a flat PNG catalog rendered from the same artwork,
#                    for older Xcode. Works everywhere but does not get the
#                    glass treatment.
#
# Local builds get the real one; INFERNO_NO_ICON=1 skips both (app ships
# with no icon at all).
compile_icon() { # compile_icon <catalog-dir> <app-icon-name>
    xcrun actool --compile "$APP" \
        --platform iphoneos \
        --minimum-deployment-target 16.0 \
        --app-icon "$2" \
        --output-partial-info-plist "$BUILD/icon.plist" \
        --include-all-app-icons \
        "$1" > /dev/null
    python3 - "$APP/Info.plist" "$BUILD/icon.plist" <<'PY'
import plistlib, sys
target, partial = sys.argv[1], sys.argv[2]
with open(target, 'rb') as f: info = plistlib.load(f)
with open(partial, 'rb') as f: extra = plistlib.load(f)
extra.pop('com.apple.actool.compilation-results', None)
info.update(extra)
with open(target, 'wb') as f: plistlib.dump(info, f)
PY
}

ICON="$ROOT/Resources/Inferno.icon"
FALLBACK_ICON="$ROOT/Resources/Assets.xcassets"
if [ -z "${INFERNO_NO_ICON:-}" ]; then
    # The probe compiles into the build directory, not /tmp, so nothing is left behind.
    mkdir -p "$BUILD/actool-probe"
    if [ -d "$ICON" ] && xcrun actool --version >/dev/null 2>&1 && \
       xcrun actool --compile "$BUILD/actool-probe" --app-icon Inferno "$ICON" >"$BUILD/actool-probe.log" 2>&1; then
        echo "==> Иконка (Icon Composer)"
        compile_icon "$ICON" Inferno
    elif [ -d "$FALLBACK_ICON" ]; then
        echo "==> Иконка (плоский .xcassets — Xcode тут старше 26, .icon не берёт)"
        compile_icon "$FALLBACK_ICON" AppIcon
    fi
fi

echo "==> Помощник для гостя (nsio)"
# Читать и писать namespace NVMe внутри гостя может только бинарник с правами:
# шеллу блочные устройства закрыты. Помощник едет в бандле, приложение кладёт
# его в гостя один раз. Без него установка .ipa не ломается — она просто идёт по
# сети, которая в разы медленнее.
if [ -z "${INFERNO_NO_NSIO:-}" ] && command -v ldid >/dev/null 2>&1; then
    mkdir -p "$APP/guest-tools"
    "$ROOT/../netlab/build-nsio.sh" "$APP/guest-tools/nsio" >/dev/null
    # The other guest tool: draws a network into the guest's status bar. It
    # needs ldid for the same reason — its entitlement is the whole point. It
    # travels packed, because the app carries it in over the console.
    "$ROOT/../netlab/build-sbnet.sh" "$BUILD/sbnet" >/dev/null
    gzip -9 -n -c "$BUILD/sbnet" > "$APP/guest-tools/sbnet.gz"
    # The agent: lives in the guest, started by launchd, and takes the app's
    # requests over the scratch namespace instead of the console. Same ldid
    # signing, same packed delivery over the console the first time. Without it
    # the app just uses the console, as it always did.
    echo "==> Guest agent (agent)"
    "$ROOT/../netlab/build-agent.sh" "$BUILD/agent" >/dev/null
    gzip -9 -n -c "$BUILD/agent" > "$APP/guest-tools/agent.gz"
else
    echo "    no ldid — building without the guest tools (no fast channel, no agent, no status bar)"
fi

echo "==> Подпись"
# The dylib is signed first: the app's seal covers it.
codesign --force --sign - --timestamp=none "$APP/Frameworks/$(basename "$DYLIB")"
if [ -n "$HVF" ]; then
    codesign --force --sign - --timestamp=none "$APP/Frameworks/Hypervisor.framework"
fi
codesign --force --sign - --timestamp=none \
    --entitlements "$ENTITLEMENTS" \
    "$APP"

echo "==> Упаковка"
cd "$BUILD"
# zip adds to an existing archive instead of replacing it, which would carry
# files from an earlier build into this one.
rm -f "$IPA"
zip -qry "$IPA" Payload -x '*.DS_Store'

echo
echo "Готово: $IPA"
ls -lh "$IPA"
